version: '2'

services:
  mule-server:
    image: 92455890/mule-server:1.0.0
    environment:
      jdeAtinaVersion: ${jdeAtinaVersion}
      JDE_USER: ${JDE_USER}
      JDE_PASSWORD: ${JDE_PASSWORD}
      JDE_ENVIRONMENT: ${JDE_ENVIRONMENT}
      JDE_ROLE: ${JDE_ROLE}
      JDE_ATINA_SERVER_NAME: ${JDE_ATINA_SERVER_NAME}
      JDE_ATINA_SERVER_PORT: ${JDE_ATINA_SERVER_PORT} 
      dragon_shopify_smtp_host: ${dragon_shopify_smtp_host}
      dragon_shopify_smtp_port: ${dragon_shopify_smtp_port}
      dragon_shopify_smtp_user: ${dragon_shopify_smtp_user}
      dragon_shopify_smtp_pass: ${dragon_shopify_smtp_pass}
      dragon_shopify_smtp_email_from: ${dragon_shopify_smtp_email_from}
      dragon_shopify_smtp_email_to: ${dragon_shopify_smtp_email_to} 
      dragon_shopify_smtp_email_errorSubject: ${dragon_shopify_smtp_email_errorSubject}
      dragon_shopify_smtp_email_msgSubject: ${dragon_shopify_smtp_email_msgSubject}
      metrics_graphite_enable: ${metrics_graphite_enable}
      metrics_graphite_server: ${metrics_graphite_server}
      metrics_graphite_port: ${metrics_graphite_port}
    container_name: mule-server
    depends_on:
     - ngrok-server
    ports:
     - "8083:8083"
     - "8081:8081"
     - "8161:8161"
    volumes:
     - /tmp/docker/mule-server/logs:/opt/mule/mule-standalone-390/logs
     - /tmp/docker/mule-server/apps:/opt/mule/mule-standalone-390/apps
    links:
     - ngrok-server:ngrok-server
    user: root
    networks:
      integradornet:
        ipv4_address: 172.29.0.5

  jde-microserver:
    image: 92455890/jdeatina-microserver:1.0.0
    environment:
      JDE_MICROSERVER_IP: ${JDE_MICROSERVER_IP}
      JDE_MICROSERVER_PORT: ${JDE_MICROSERVER_PORT}  
      JDE_MICROSERVER_CODE: ${JDE_MICROSERVER_CODE}
      JDE_MICROSERVER_JDE_LIB_WRAPPED: ${JDE_MICROSERVER_JDE_LIB_WRAPPED}
      JDE_MICROSERVER_STD_WEB_SERVICE: ${JDE_MICROSERVER_STD_WEB_SERVICE}
      JDE_MICROSERVER_SECRET_KEY: ${JDE_MICROSERVER_SECRET_KEY}
      JDE_MICROSERVER_TOKEN_EXPIRATION: ${JDE_MICROSERVER_TOKEN_EXPIRATION}
    container_name: jdeatina-microserver
    ports:
     - "${JDE_MICROSERVER_PORT}:${JDE_MICROSERVER_PORT}"
    volumes:
     - /tmp/jde/config:/tmp/jde/config
     - /tmp/jde/lib:/tmp/jde/lib
    user: root
    networks:
      integradornet:
        ipv4_address: 172.29.0.3
    restart: always 
        
  ngrok-server:
    image: 92455890/ngrok-server:1.0.0
    environment:
      NGROK_NGROK_TOKEN: ${NGROK_NGROK_TOKEN}
      NGROK_MULE_SERVER_HOST: ${NGROK_MULE_SERVER_HOST}
      NGROK_MULE_SERVER_PORT: ${NGROK_MULE_SERVER_PORT}
    ports:
      - "4040:4040"
    container_name: ngrok-server
    networks:
      integradornet:
        ipv4_address: 172.29.0.2    
    
networks:
  integradornet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.29.0.0/16
         gateway: 172.29.0.1
