version: '2'

services:
    
  jde-microserver:
    image: 92455890/jdeatina-server:1.0.0
    environment:
      JDE_MICROSERVER_IP: ${JDE_MICROSERVER_IP}
      JDE_MICROSERVER_PORT: ${JDE_MICROSERVER_PORT}  
      JDE_MICROSERVER_CODE: ${JDE_MICROSERVER_CODE}
      JDE_MICROSERVER_JDE_LIB_WRAPPED: ${JDE_MICROSERVER_JDE_LIB_WRAPPED}
      JDE_MICROSERVER_STD_WEB_SERVICE: ${JDE_MICROSERVER_STD_WEB_SERVICE}
      JDE_MICROSERVER_SECRET_KEY: ${JDE_MICROSERVER_SECRET_KEY}
      JDE_MICROSERVER_TOKEN_EXPIRATION: ${JDE_MICROSERVER_TOKEN_EXPIRATION}
    container_name: jdeatina-server
    ports:
     - "${JDE_MICROSERVER_PORT}:${JDE_MICROSERVER_PORT}"
    volumes:
     - /tmp/jde/config:/tmp/jde/config
     - /tmp/jde/lib:/tmp/jde/lib
    user: root
    networks:
      jde_atinanet:
        ipv4_address: 172.27.0.2
    restart: always 
     
    
networks:
  jde_atinanet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.27.0.0/16
         gateway: 172.27.0.1
