version: '2'

services:
  jde-microserver:
    image: 92455890/jdeatina-microserver:1.0.0
    environment:
      JDE_MICROSERVER_IP: ${JDE_MICROSERVER_IP}
      JDE_MICROSERVER_PORT: ${JDE_MICROSERVER_PORT}  
      JDE_MICROSERVER_CODE: ${JDE_MICROSERVER_CODE}
      JDE_LIB_WRAPPED_VERSION: ${JDE_LIB_WRAPPED_VERSION}
      STD_WEB_SERVICE_VERSION: ${STD_WEB_SERVICE_VERSION}
      JDE_ATINA_SERVER_VERSION: ${JDE_ATINA_SERVER_VERSION}
      JDE_MICROSERVER_SECRET_KEY: ${JDE_MICROSERVER_SECRET_KEY}
      JDE_MICROSERVER_TOKEN_EXPIRATION: ${JDE_MICROSERVER_TOKEN_EXPIRATION}
      JDE_MICROSERVER_ENTERPRISE_SERVER_NAME: ${JDE_MICROSERVER_ENTERPRISE_SERVER_NAME}
      JDE_MICROSERVER_ENTERPRISE_SERVER_IP: ${JDE_MICROSERVER_ENTERPRISE_SERVER_IP}
      JDE_MICROSERVER_ENTERPRISE_DB_NAME: ${JDE_MICROSERVER_ENTERPRISE_DB_NAME}
      JDE_MICROSERVER_ENTERPRISE_DB_IP: ${JDE_MICROSERVER_ENTERPRISE_DB_IP}
      ATINA_REPOSITORY_PROTOCOL: ${ATINA_REPOSITORY_PROTOCOL}
      ATINA_REPOSITORY_URL: ${ATINA_REPOSITORY_URL}
      CUSTOMER_REPOSITORY_PROTOCOL: ${CUSTOMER_REPOSITORY_PROTOCOL}
      CUSTOMER_REPOSITORY_URL: ${CUSTOMER_REPOSITORY_URL}
      JDE_MICROSERVER_MOCKING: ${JDE_MICROSERVER_MOCKING}
    container_name: jdeatina-microserver
    ports:
     - "${JDE_MICROSERVER_PORT}:${JDE_MICROSERVER_PORT}"
    volumes:
     - /tmp/jde-microserver:/tmp/jde
    user: root
    restart: always
    networks:
      atinacloud:
        ipv4_address: 172.40.0.1      
         
    
networks:
  atinacloud:
    driver: bridge
    ipam:
     config:
       - subnet: 172.40.0.0/16
         gateway: 172.40.0.1    