version: '2'

services:
  jde-microserver:
    image: 92455890/jdeatina-microserver:1.0.0
    environment:
      JDE_MICROSERVER_IP: ${JDE_MICROSERVER_IP}
      JDE_MICROSERVER_PORT: ${JDE_MICROSERVER_PORT}  
      JDE_MICROSERVER_CODE: ${JDE_MICROSERVER_CODE}
      JDE_LIB_WRAPPED_VERSION: ${JDE_LIB_WRAPPED_VERSION}
      STD_WEB_SERVICE_VERSION: ${STD_WEB_SERVICE_VERSION}
      JDE_ATINA_SERVER_VERSION: ${JDE_ATINA_SERVER_VERSION}
      JDE_MICROSERVER_SECRET_KEY: ${JDE_MICROSERVER_SECRET_KEY}
      JDE_MICROSERVER_TOKEN_EXPIRATION: ${JDE_MICROSERVER_TOKEN_EXPIRATION}
      JDE_MICROSERVER_ENTERPRISE_SERVER_NAME: ${JDE_MICROSERVER_ENTERPRISE_SERVER_NAME}
      JDE_MICROSERVER_ENTERPRISE_SERVER_IP: ${JDE_MICROSERVER_ENTERPRISE_SERVER_IP}
      JDE_MICROSERVER_ENTERPRISE_DB_NAME: ${JDE_MICROSERVER_ENTERPRISE_DB_NAME}
      JDE_MICROSERVER_ENTERPRISE_DB_IP: ${JDE_MICROSERVER_ENTERPRISE_DB_IP}
      ATINA_REPOSITORY_PROTOCOL: ${ATINA_REPOSITORY_PROTOCOL}
      ATINA_REPOSITORY_URL: ${ATINA_REPOSITORY_URL}
      CUSTOMER_REPOSITORY_PROTOCOL: ${CUSTOMER_REPOSITORY_PROTOCOL}
      CUSTOMER_REPOSITORY_URL: ${CUSTOMER_REPOSITORY_URL}
      JDE_MICROSERVER_MOCKING: ${JDE_MICROSERVER_MOCKING}
    container_name: jdeatina-microserver
    ports:
     - "${JDE_MICROSERVER_PORT}:${JDE_MICROSERVER_PORT}"
    volumes:
     - /tmp/jde-microserver:/tmp/jde
    user: root
    restart: always
    networks:
      atinacloud:
        ipv4_address: 172.33.0.1      
        
  jde-mule-server:
    image: 92455890/jde-mule-server:1.0.0
    environment:
      jdeAtinaVersion: ${jdeAtinaVersion}
      JDE_CONNECTOR_USER: ${JDE_CONNECTOR_USER}
      JDE_CONNECTOR_PASSWORD: ${JDE_CONNECTOR_PASSWORD}
      JDE_CONNECTOR_ENVIRONMENT: ${JDE_CONNECTOR_ENVIRONMENT}
      JDE_CONNECTOR_ROLE: ${JDE_CONNECTOR_ROLE}
      JDE_CONNECTOR_MICROSERVER_NAME: ${JDE_CONNECTOR_MICROSERVER_NAME}
      JDE_CONNECTOR_MICROSERVER_PORT: ${JDE_CONNECTOR_MICROSERVER_PORT} 
      dragon_shopify_smtp_host: ${dragon_shopify_smtp_host}
      dragon_shopify_smtp_port: ${dragon_shopify_smtp_port}
      dragon_shopify_smtp_user: ${dragon_shopify_smtp_user}
      dragon_shopify_smtp_pass: ${dragon_shopify_smtp_pass}
      dragon_shopify_smtp_email_from: ${dragon_shopify_smtp_email_from}
      dragon_shopify_smtp_email_to: ${dragon_shopify_smtp_email_to} 
      dragon_shopify_smtp_email_errorSubject: ${dragon_shopify_smtp_email_errorSubject}
      dragon_shopify_smtp_email_msgSubject: ${dragon_shopify_smtp_email_msgSubject}
      metrics_graphite_enable: ${metrics_graphite_enable}
      metrics_graphite_server: ${metrics_graphite_server}
      metrics_graphite_port: ${metrics_graphite_port}
      REPOSITORY_PROTOCOL: ${REPOSITORY_PROTOCOL}
      REPOSITORY_URL: ${REPOSITORY_URL}
    container_name: jde-mule-server
    ports:
     - "8083:8083"
     - "8084:8084"
     - "8092:8081"
     - "8161:8161"
    volumes:
     - /tmp/jde-mule-server:/opt/mule/mule-standalone-390
    user: root  
    networks:
      atinacloud:
        ipv4_address: 172.33.0.2
        
  graphite-server:
    image: kamon/grafana_graphite
    volumes:
      - /home/jde-grafana-data:/opt/grafana/data
    ports:
      - "2003:2003"
      - "2004:2004"
      - "8080:80"
      - "8088:81"
      - "8125:8125"
      - "8126:8126"
    container_name: jde-graphite-server
    user: root
    networks:
      integradornet:
        ipv4_address: 172.33.0.3
    restart: always        
    
networks:
  atinacloud:
    driver: bridge
    ipam:
     config:
       - subnet: 172.33.0.0/16
         gateway: 172.33.0.1    