version: '2'

services:
  jde-mule-server:
    image: 92455890/jde-mule-server:1.0.0
    environment:
      jdeAtinaVersion: ${jdeAtinaVersion}
      JDE_CONNECTOR_USER: ${JDE_CONNECTOR_USER}
      JDE_CONNECTOR_PASSWORD: ${JDE_CONNECTOR_PASSWORD}
      JDE_CONNECTOR_ENVIRONMENT: ${JDE_CONNECTOR_ENVIRONMENT}
      JDE_CONNECTOR_ROLE: ${JDE_CONNECTOR_ROLE}
      JDE_CONNECTOR_MICROSERVER_NAME: ${JDE_CONNECTOR_MICROSERVER_NAME}
      JDE_CONNECTOR_MICROSERVER_PORT: ${JDE_CONNECTOR_MICROSERVER_PORT} 
      dragon_shopify_smtp_host: ${dragon_shopify_smtp_host}
      dragon_shopify_smtp_port: ${dragon_shopify_smtp_port}
      dragon_shopify_smtp_user: ${dragon_shopify_smtp_user}
      dragon_shopify_smtp_pass: ${dragon_shopify_smtp_pass}
      dragon_shopify_smtp_email_from: ${dragon_shopify_smtp_email_from}
      dragon_shopify_smtp_email_to: ${dragon_shopify_smtp_email_to} 
      dragon_shopify_smtp_email_errorSubject: ${dragon_shopify_smtp_email_errorSubject}
      dragon_shopify_smtp_email_msgSubject: ${dragon_shopify_smtp_email_msgSubject}
      metrics_graphite_enable: ${metrics_graphite_enable}
      metrics_graphite_server: ${metrics_graphite_server}
      metrics_graphite_port: ${metrics_graphite_port}
      REPOSITORY_PROTOCOL: ${REPOSITORY_PROTOCOL}
      REPOSITORY_URL: ${REPOSITORY_URL}
    container_name: jde-mule-server
    ports:
     - "8083:8083"
     - "8084:8084"
     - "8092:8081"
     - "8161:8161"
    volumes:
     - /tmp/docker/jde-mule-server:/opt/mule/mule-standalone-390
    user: root